name: minecraft_ai_bot
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - pandas
  - openpyxl
  - requests
  - pysimplegui
  - pip:
    - ollama
    - numpy
